name: Caching Test

on:
  workflow_dispatch:
    inputs:
      artifact-action:
        required: true
        type: choice
        default: ''
        options:
          - save
          - restore

jobs:
  caching-test:
    runs-on: ubuntu-24.04
    steps:
    - if: github.event.inputs.artifact-action == 'save'
      run: |
        mkdir tmp/
        echo ${{ github.run_id }} > tmp/test.txt
        cat tmp/test.txt
    - if: github.event.inputs.artifact-action == 'save'
      uses: actions/cache/save@v4
      id: cache
      with:
        path: tmp/
        key: chache-hoge-${{ github.run_id }}
    - if: github.event.inputs.artifact-action == 'restore'
      uses: actions/cache/restore@v4
      id: resotre-cache
      with:
        path: tmp/
        key: chache-hoge-
    - if: github.event.inputs.artifact-action == 'restore'
      run: |
        cat tmp/test.txt
