name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  sandbox-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Repository ${{ github.repository }}"
      - name: Git Recent Commit History
        run: git log --oneline -5

