name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  sandbox-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.sha: ${{ github.sha }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Git Recent Commit History
        run: git log --oneline -5
