name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Manual Workflow"
      - name: Check out repository
        uses: actions/checkout@v4
