name: GitHub Actions

on:
  pull_request:

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.sha: ${{ github.sha }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
      - name: Check out repository
        uses: actions/checkout@v4
      - run: git log --oneline -5
  