name: Push Actions(release and PR)

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.sha: ${{ github.sha }}"
      - name: Check out repository
        uses: actions/checkout@v4
      - run: git log --oneline -5
