name: Send slack message

on:
  workflow_dispatch:

env:
  PULL_REQUEST_HEAD: ${{ github.sha }}

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.PULL_REQUEST_HEAD }}
